import './globals.css';
import { Inter } from 'next/font/google';
import TopBar from '@/global-components/TopBar';
import Footer from '@/global-components/Footer';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className} suppressHydrationWarning={true}>
        <TopBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}

export default RootLayout;
